### PR TITLE
do a bunch of refactoring, just to fix default cargo loading time adjustment..

### LINKED ISSUE #67: fix automatic cargo loading time adjustment after introducing warp time config
Just figured. The code adds a constant 420 seconds to cargo loading time if more than one run. This is to take in account for the warping and other sleeps for a run. Just a thought. Might not make any sense "fixing it" in this pr

_Originally posted by @sillychipmunk in https://github.com/x-actly/Eve-Online-Mining-Bot/issues/66#issuecomment-2105683652_

### PR DESCRIPTION
**Pull request by sillychipmunk**
fixes #67

### CODE REVIEW

**Comment by sillychipmunk** [comment]
funny, i think  i must be using a different version of python locally. need to test ;)

**Comment by sillychipmunk** [comment]
ah that explains hadnt included mypy in the check script :P

**Comment by sillychipmunk** [comment]
@x-actly the time came around eventually, to move files around a bit. This time mostly to make it possible to import modules into tests without making wierd magic

**Comment by sillychipmunk** [comment]
@x-actly folder structure is highly debatable.

**Comment by x-actly** [comment]
How do you mean that? I fully agree for a more organized folder structure.

**Comment by sillychipmunk** [comment]
> How do you mean that? I fully agree for a more organized folder structure.

renamed Bot/main.py to Bot/bot.py :) im good now. was too many mains

**Review by x-actly — APPROVED** [review]
ready when u are? 🌞

**Comment by sillychipmunk** [comment]
Forgot to say @x-actly i only tested i could open the bot 😂

**Pull request merged**
