### PR TITLE
add a config handler class + make cross platform

### LINKED ISSUE #18: Find a way to make it portable to linux and macos
the windll package needs to be used for windows. find ways for the other OSes

### LINKED ISSUE #45: Add a test button beside each location field that moves the mouse to that location
The clear cargo has a test button. All the other coords inputs should have the same. A button that immediately moves the mouse to the coords. 

The clear cargo is the only "composite test button". And will remain as that.

### LINKED ISSUE #47: Need to be able to disable shield hardener for mining in high sec
when you have 5 drones, you will never die in highsec other than by players

I think the most natural default is no shield hardener activation. We can make a section in readme for how to enable it

### PR DESCRIPTION
**Pull request by sillychipmunk**
~needs to be tested, this is developed on a mac which doesn't support win api and I cant get Tk working~ <- fixed it, installed python from official site

- [x] Test on macOS (~albeit very limited to how easy it is to use.. and need to find a way to get mouse location~)
- [x] Test on Windows (should "just" work)
- [ ] Test on Linux (~need to find a way to get mouse location~) (can be skipped, dont want to bring up a linux just to test)

It seemed pyautogui had a mouse location function that is cross platform

fixes #18 
fixes #47 (by the fact that an empty string split by comma will yield an empty array which does nothing)
fixes #45 (not for the belt coords though)

@x-actly for the issue of disabling default hardener logic, I have removed the default "F3". We can discuss if we want it as default, but I think given the name of the repo and its intention to be used mainly in highsec the importance of drones cannot be underestimated. To activate a set of combos to execute when leaving station now, you set them as a comma separated string in hardener_keys in [SETTINGS] like this 

```
[SETTINGS]
hardener_keys = F3, Alt-F2, Alt-F1
```

### CODE REVIEW

**Comment by sillychipmunk** [comment]
not bad for a tiny bot:

```markdown
       4 text files.
       4 unique files.
       0 files ignored.

github.com/AlDanial/cloc v 2.00  T=0.01 s (405.1 files/s, 100882.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                           4            219            119            658
-------------------------------------------------------------------------------
SUM:                             4            219            119            658
-------------------------------------------------------------------------------
```

**Comment by sillychipmunk** [comment]
hmm maybe I could even disable the whole eve window selection label and combo box when its not supported by the platform 🤔

**Comment by sillychipmunk** [comment]
image

**Comment by sillychipmunk** [comment]
I decided to show an estimation of time to complete that changes when you update runs, hold or yield. Should maybe show it as decreasing reset timer like before But it was not trivial 😅

**Comment by x-actly** [comment]
works for with new fix "get_cargo_loading_time" ;)

**Comment by sillychipmunk** [comment]
> works for with new fix "get_cargo_loading_time" ;)
> 
> 

Ill say as Siri "I'm sorry, I didn't get that" 😂

**Comment by x-actly** [comment]
> > works for with new fix "get_cargo_loading_time" ;)
> 
> Ill say as Siri "I'm sorry, I didn't get that" 😂

I had a zero division issue when I tested the pull request, but you had fixed it in the meantime. All good :D
image

**Pull request merged**
