### PR TITLE
use properties file and fail if not present

### PR DESCRIPTION
**Pull request by jarlah**
putting config into properties could make it possible to load a "profile" at some point. Maybe it could take the path to the properties file in a command line argument. right now just reads the config.properties in current dir

- [x] removed packages not found in requirements.txt
- [x] replaced config folder with properties file
- [x] minor touch up
- [x] tested running the program on windows 11 with latest python 3 from microsoft store
- [ ] should propably not save the run time
- [ ] test in-game

### CODE REVIEW

**Comment by jarlah** [comment]
Its having an ackward double reset when testing here 😂 so 2 x mining/reset for each reset. 😂 guess its just a copy paste bummer ;)

**Comment by x-actly** [comment]
Hey, thanks a lot for your pull request. As you can see from the project, I'm no pro, but I definitely appreciate any improvements. When I started the project, I just wanted to mine a bit on a laptop on the side without having to constantly worry about it every few minutes.

**Comment by jarlah** [comment]
the 5 hours test results (with some logging added for the sleeping): 
[logs.txt](https://github.com/x-actly/Eve-Online-Mining-Bot/files/15183733/logs.txt)
:) seemed to work flawlessly :)

**Comment by jarlah** [comment]
> Hey, thanks a lot for your pull request. As you can see from the project, I'm not professional programmer, but I definitely appreciate any improvements. When I started the project, I just wanted to mine a bit on a laptop on the side without having to constantly worry about it every few minutes.

to not be a professional programmer its quite a good project. Its not just about the code you know, its about the utility and presentation too ;) nice work :)

**Comment by x-actly** [comment]
to your edit... I used the bot from October to December last year, for about 10 to 20 hours per week, on an omega account, and neither got caught by CCP nor reported by any other player. Recently, a player on Reddit contacted me, who has been using the bot irregularly since December and has not been caught either. I'm not even sure if CCP uses server-side tools to detect bots. I think as long as you're not botting 24/7, you should be relatively safe

**Comment by jarlah** [comment]
yeah I also dont think its possible nor interesting for eve to monitor for how keystrokes are executed or how the mouse is moved .. I mean literally we are not even touching eve. We are just moving and interacting with mouse and keyboard. Which is pretty normal for accessibility reasons alone

**Comment by jarlah** [comment]
its another thing with Sanderling and the eve memory model mapping. That's a totally different story

**Pull request merged**
