### PR TITLE
add warping time

### PR DESCRIPTION
**Pull request by x-actly**
#62 

@sillychipmunk I've already created the pull request now since I might use the bot in nullsec mining anomalies tonight, some of which are more than 80 AU away. Is there anything else you'd like to address with the changes?

### CODE REVIEW

**Comment by sillychipmunk** [comment]
You propably dont need the set method. Thats only for things we manage in UI

**Comment by sillychipmunk** [comment]
I think you meant to reference #62

**Comment by x-actly** [comment]
kk, this make sense!

**Comment by sillychipmunk** [comment]
to fix formatting issues and check code you can run ./check.bat

**Comment by sillychipmunk** [comment]
Just figured. The code adds a constant 420 seconds to cargo loading time if more than one run. This is to take in account for the warping and other sleeps for a run. Just a thought. Might not make any sense "fixing it" in this pr

**Review by sillychipmunk — APPROVED** [review]
LGTM (real enterprisy of me 😆 )

**Comment by x-actly** [comment]
> LGTM (real enterprisy of me 😆 )

haha, i had to google that first!

**Pull request merged**
